waypoints:
  - x: -2.35
    y: -0.332
    z: 0.448
    id: "start_point"


  - x: 1.1
    y: 1.1
    z: 1.1
    id: "point_1"


  - x: 2.1
    y: 2.1
    z: 2.1
    id: "point_2"

  - x: 3.1
    y: 3.1
    z: 3.1
    id: "point_3"

  - x: 4.1
    y: 4.1
    z: 4.1
    id: "end_point"
